services:
  postgres:
    image: postgres:latest
    container_name: locator-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: locator
    ports:
      - "5432:5432"
    restart: unless-stopped

#  docker-compose -f db.yml up
